name: Create Package

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Package
        run: yarn pack

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: invxwatermark-v${{ github.event.release.tag_name }}.tgz
          path: ./invxwatermark-v${{ github.event.release.tag_name }}.tgz

      - name: Get Release ID
        id: get_release
        run: echo "::set-output name=release_id::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.id')"

      - name: Download Package
        uses: actions/download-artifact@v2
        with:
          name: invxwatermark-v${{ github.event.release.tag_name }}.tgz

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.release_id }}/assets{?name,label}
          asset_content_type: application/gzip
          asset_path: ./invxwatermark-v${{ github.event.release.tag_name }}.tgz
          asset_name: invxwatermark-v${{ github.event.release.tag_name }}.tgz
        env:
          GITHUB_TOKEN: ${{ github.token }}